### PR TITLE
support deploymentBucket parameter

### PR DESCRIPTION
**Pull request by hideokamoto**
I wanna define the stack's deployment bucket.
So could you support to overwrite deploymentBucket parameters in `config.yml` ?
https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

Thanks !

### CODE REVIEW

**Comment by k1LoW** [comment]
Hi @hideokamoto Thank you for your commit !!! ( and I'm sorry for the late reply. )

I have 1 question.

Why you want to overwite deploymentBucket parameters ?

---

CI is broken. I'll fix it

**Comment by hideokamoto** [comment]
We are maintaining multiple serverless stacks in our AWS account.
For default, the Serverless Framework will create S3 bucket per stack, but we wanna use a single bucket to upload Serverless Application for deployment.

So we want to overwrite deployment bucket in your application.

**Comment by k1LoW** [comment]
> For default, the Serverless Framework will create S3 bucket per stack, but we wanna use a single bucket to upload Serverless Application for deployment.

nrhd~!

Thank you !!!

**Comment by k1LoW** [comment]
I think `deploymentBucket` should be optional ( and hidden parameter like `FAULTLINE_DYNAMODB_TABLE_SUFFIX` ) . Because most user do not deploy multiple faultline.


So,  could you set `deploymentBucket` param like https://github.com/faultline/faultline/blob/34a326196102a30a7a0acaa67ae9c2996f9169f7/.serverless_plugins/faultline-resources/index.js#L246-L248

**Comment by k1LoW** [comment]
Released as v1.5.0.

**Pull request merged**
